[versions]
gradlePluginVersion = "8.13.0"

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "gradlePluginVersion" }
androidApplication = { id = "com.android.application", version.ref = "gradlePluginVersion" }